cache:
  paths:
    - node_modules

include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test:coverage
  coverage: /^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/
  only:
    - development