name: test

on:
  push:
    branches: [ development ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test:coverage
